[package]
name    = "contixis-codec"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow     = { workspace = true }
thiserror  = { workspace = true }
tracing    = { workspace = true }
tokio      = { workspace = true }
bytes      = { workspace = true }
zstd       = { workspace = true }
