[package]
name    = "contixis-host"
version.workspace = true
edition.workspace = true

[lib]
name = "contixis_host_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "contixis-host"
path = "src/main.rs"

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri        = { workspace = true }
tauri-plugin-shell = { workspace = true }
anyhow       = { workspace = true }
thiserror    = { workspace = true }
tracing      = { workspace = true }
tracing-subscriber = { workspace = true }
tokio        = { workspace = true }
parking_lot  = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
uuid         = { workspace = true }
dirs         = { workspace = true }
hex          = { workspace = true }
quinn        = { workspace = true }
rustls       = { workspace = true }
prost        = { workspace = true }
rand         = { workspace = true }
dashmap      = { workspace = true }
arboard      = { workspace = true }
contixis-proto  = { path = "../../../crates/contixis-proto" }
contixis-crypto = { path = "../../../crates/contixis-crypto" }
contixis-core   = { path = "../../../crates/contixis-core" }
contixis-net    = { path = "../../../crates/contixis-net" }
contixis-input  = { path = "../../../crates/contixis-input" }

[target.'cfg(target_os = "linux")'.dependencies]
x11 = { version = "2", features = ["xlib", "xrandr"] }
